[server]
host = "0.0.0.0" 
port = 8080 
sizeLimit = 125 # MB
enableH2C = "on" # "on" or "off"
debug = false

[httpc]
mode = "auto" # "auto" or "advanced"
maxIdleConns = 100 # only for advanced mode
maxIdleConnsPerHost = 60 # only for advanced mode
maxConnsPerHost = 0 # only for advanced mode

[pages]
enabled = false
staticDir = "/data/www" 

[log]
logFilePath = "/data/ghproxy/log/ghproxy.log" 
maxLogSize = 5 # MB
level = "info" # dump, debug, info, warn, error, none

[cors]
enabled = true

[auth]
authMethod = "parameters" # "header" or "parameters"
authToken = "token"
enabled = false
passThrough = false

[blacklist]
blacklistFile = "/data/ghproxy/config/blacklist.json"
enabled = false

[whitelist]
enabled = false
whitelistFile = "/data/ghproxy/config/whitelist.json"

[rateLimit]
enabled = false
rateMethod = "total" # "ip" or "total"
ratePerMinute = 180
burst = 5

[outbound]
enabled = false
url = "socks5://127.0.0.1:1080" # "http://127.0.0.1:7890"